import { test, expect } from '@playwright/test'

test('service ribbon, project previews and legal content follow the selected language', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/?lang=es')
  await expect(page.locator('.services-ribbon')).toContainText('IA Y AUTOMATIZACIÓN')
  await expect(page.locator('.services-ribbon')).toContainText('E-COMMERCE')
  await expect(page.locator('.hero-legal-link')).toHaveText('Términos y Condiciones')
  await expect(page.locator('.project-visual.orbit').first()).toContainText('Descubrí la colección')
  await page.getByRole('button', { name: 'EN', exact: true }).first().click()
  await expect(page.locator('.services-ribbon')).toContainText('AI & AUTOMATION')
  await expect(page.locator('.hero-legal-link')).toHaveText('Terms & Conditions')
  await expect(page.locator('.project-visual.orbit').first()).toContainText('Discover the collection')
  await page.getByRole('contentinfo').getByRole('link', { name: 'Terms & Conditions', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('50% upfront payment')
  await expect(page.locator('.terms-content')).toHaveAttribute('lang', 'en')
  await page.keyboard.press('Escape')
  await page.goto('/terms/en/')
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('Terms & Conditions')
  await expect(page.locator('main section')).toHaveCount(22)
  await expect(page.locator('main')).toContainText('50% upfront payment')
  await expect(page.locator('svg, canvas')).toHaveCount(0)
  await page.getByRole('link', { name: 'ES', exact: true }).click()
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('Términos y Condiciones')
  await expect(page.locator('main')).toContainText('50% de anticipo')
})
